export const fakeProducts1 = [
  {
    id: 1,
    imageSource: '/images/pates_fettuccines_carbonara.png',
    title: 'Pâtes carbonara',
    price: 12.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: '/images/pates_fettuccines_escaloppe_poulet_champi_poivrons_harricots.png',
    title: 'Pâtes au poulet',
    price: 14.79,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

export const fakeProductsPasta = [
  {
    id: 1,
    imageSource: '/images/pates_fettuccines_carbonara.png',
    title: 'Fettuccines Carbonara',
    price: 12.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: '/images/pates_fettuccines_escaloppe_poulet_champi_poivrons_harricots.png',
    title: 'Fettuccines Poulet',
    price: 16.79,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    imageSource: '/images/pates_fusili_tomates_basilic.png',
    title: 'Fusilis Napolitaine',
    price: 11.99,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 4,
    imageSource: '/images/pates_macaronis_bolo_gruyere_basilic.png',
    title: 'Macaronis Bolognaise',
    price: 15.79,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 5,
    imageSource: '/images/pates_spaggethis_bolognaise_parmesan.png',
    title: 'Spaghettis Bolognaise',
    price: 15.79,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 6,
    imageSource: '/images/pates_spagettis_sauce_tomate_mozza_basilic.png',
    title: 'Spaghettis Mozzarella',
    price: 12.99,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 7,
    imageSource: '/images/pates_lasagnes_bolognaise.png',
    title: 'Lasagnes Bolognaise',
    price: 17.99,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

export const fakeProductsPizza = [
  {
    id: 1,
    imageSource: '/images/pizza_4_fromages.png',
    title: 'Pizza 4 fromages',
    price: 14.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: '/images/pizza_calzone.png',
    title: 'Pizza Calzone',
    price: 14.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    imageSource: '/images/pizza_chorizo_fondue.png',
    title: 'Pizza Chorizo',
    price: 15.79,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 4,
    imageSource: '/images/pizza_vege_tomates_olives.png',
    title: 'Pizza Vege',
    price: 11.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 5,
    imageSource: '/images/pizza_margherita.png',
    title: 'Pizza Margherita',
    price: 10.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 6,
    imageSource: '/images/pizza_saladiere_jambon_2olives_mais_champignon_tomate_basilic.png',
    title: 'Pizza Carnaval',
    price: 14.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 7,
    imageSource: '/images/pizza_thon_tomate_oignon.png',
    title: 'Pizza Thon',
    price: 13.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

export const fakeProductsSalade = [
  {
    id: 1,
    imageSource: '/images/accompagnement_salade_saumon.png',
    title: 'Salade Saumon',
    price: 14.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: '/images/accompagnement_salade.png',
    title: 'Salade Vege',
    price: 11.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    imageSource: '/images/accompagnement_spaghetti__tomates_basilic.png',
    title: 'Salade Pasta',
    price: 12.9999,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];
